### ISSUE TITLE
Technical checklist for go-live

### ISSUE THREAD

**Issue by alanorth** [Gizra/IBLI#180]
Checklist for go-live by August 31st:
- [x] update external DNS for ibli.ilri.org
- [x] update internal DNS ibli.ilri.org
- [ ] update firewall settings on web server (public TCP 80, etc)
- [ ] create account / database on central MySQL server (for reference, DNS name: boran.ilri.cgiar.org)

@niryariv I'm just brainstorming a list of things I need to do with the host for going live.

**Comment by niryariv** [comment]
@alanorth didn't understand the last one - is that on ILRI's MySQL?

**Comment by alanorth** [comment]
@niryariv Yeah, sorry... we usually use a central MySQL server instead of installing MySQL on all the different machines.  Just makes it easier to maintain / backup / update.  Have you guys already loaded MySQL on the server?

**Comment by niryariv** [comment]
haven't installed yet, since currently only the IDL/Matlab code is on the server while the site is being developed on an external machine. Shouldn't be a big deal, assuming the DB location would be transparent to the PHP side.

**Comment by alanorth** [comment]
@niryariv exactly.  And you can already pencil in a DB server DNS name.  Assuming we'll use something like "ibli_blah" for username and database name as well.  I can create this on a moment's notice when we're ready.

**Comment by alanorth** [comment]
Ok, the internal ILRI DNS is updated.  This is important, because users inside the ILRI campus use a different DNS server than external users!

**Comment by niryariv** [comment]
We're ready to push the site to a live server. 

@alanorth would it be ok if we use the [Pantheon](https://www.gotpantheon.com/pricing) live environment initially until we're ready to deploy on ILRI's servers? It's a single click deployment and the $25/mo plan should be fine. Later we'll just point the domain to ILRI when we're ready.

@bnedavies is it ok if we remove the login so anyome can access the site & Google can index it? This can be a quiet launch for now, to let it get some Google traction and early users.

**Comment by alanorth** [comment]
@niryariv I don't mind either way.  IBLI has to approve the costs, but I don't mind either way.  We're still doing IDL and Matlab on the ILRI server though, right?

**Comment by niryariv** [comment]
@alanorth yes, keeping IDL/Matlab on the ILRI server.

**Comment by bnedavies** [comment]
@niryariv I think better to keep login for now actually...

**Comment by niryariv** [comment]
ok - pushed to live, login in place: http://live-ibli.gotpantheon.com/

**Comment by niryariv** [comment]
@alanorth the server is ready, you can point the domain:

`ibli.ilri.org    CNAME   edge.live.getpantheon.com`

**Comment by alanorth** [comment]
@niryariv Ah! I didn't see this.  Let me request this immediately.

**Comment by niryariv** [comment]
great, thanks!

**Comment by alanorth** [comment]
It's live!

``` console
$ host ibli.ilri.org
ibli.ilri.org is an alias for edge.live.getpantheon.com.
edge.live.getpantheon.com has address 162.209.95.41
edge.live.getpantheon.com has address 23.253.171.29
edge.live.getpantheon.com has address 23.253.58.199
edge.live.getpantheon.com has IPv6 address 2001:4801:7827:104:be76:4eff:fe11:606e
edge.live.getpantheon.com has IPv6 address 2001:4801:7824:102:be76:4eff:fe10:88d0
edge.live.getpantheon.com has IPv6 address 2001:4801:7825:101:be76:4eff:fe10:46f7
```

**Comment by niryariv** [comment]
nice!

any remaining tasks in this ticket, or can we close it?
